import { useState } from 'react'
import { format, parseISO } from 'date-fns'
import { ClipboardCopy, Printer, RefreshCw, FileText, Check } from 'lucide-react'
import { ROLES } from '../../data/models.js'
import clsx from 'clsx'

// Builds a plain-text version of the summary for clipboard copy
function buildPlainText(production, bible, includeFF) {
  const b = bible
  const lines = []

  lines.push('═══════════════════════════════════════')
  lines.push('PRODUCTION HANDOFF SUMMARY')
  lines.push('Generated by Balance — Orbital Studios')
  lines.push(`Date: ${format(new Date(), 'MMMM d, yyyy h:mm a')}`)
  lines.push('═══════════════════════════════════════')
  lines.push('')

  // Production details
  lines.push('PRODUCTION')
  lines.push(`Name:     ${production.name}`)
  lines.push(`Client:   ${production.client || '—'}`)
  lines.push(`Status:   ${production.status}`)
  lines.push(`Type:     ${production.productionType}`)
  lines.push(`Location: ${production.locationType === 'In-House (Orbital Studios)' ? 'Orbital Studios' : production.locationAddress || 'Mobile'}`)
  if (production.startDate) {
    const dateStr = `${format(parseISO(production.startDate), 'MMM d, yyyy')}${production.endDate ? ` – ${format(parseISO(production.endDate), 'MMM d, yyyy')}` : ''}`
    lines.push(`Dates:    ${dateStr}`)
  }
  lines.push('')

  // Key Players
  if (b.keyPlayers?.length > 0) {
    lines.push('KEY PLAYERS')
    lines.push('─────────────────────────────────────')
    b.keyPlayers.forEach(p => {
      lines.push(`${p.name} — ${p.role || ''}${p.company ? ` (${p.company})` : ''} [${p.tag}]`)
      if (p.phone) lines.push(`  Phone: ${p.phone}`)
      if (p.email) lines.push(`  Email: ${p.email}`)
      if (p.notes) lines.push(`  Notes: ${p.notes}`)
    })
    lines.push('')
  }

  // Documents received
  if (b.documents?.length > 0) {
    lines.push('DOCUMENTS RECEIVED')
    lines.push('─────────────────────────────────────')
    b.documents.forEach(d => {
      const dateStr = d.dateReceived ? ` (received ${format(parseISO(d.dateReceived), 'MMM d, yyyy')})` : ''
      lines.push(`• ${d.name}${dateStr}`)
      if (d.notes) lines.push(`  ${d.notes}`)
    })
    lines.push('')
  }

  // Open concerns
  const openConcerns = b.concerns?.filter(c => c.status === 'Open') || []
  if (openConcerns.length > 0) {
    lines.push('OPEN CONCERNS')
    lines.push('─────────────────────────────────────')
    const order = { High: 0, Medium: 1, Low: 2 }
    openConcerns
      .sort((a, b) => order[a.severity] - order[b.severity])
      .forEach(c => {
        lines.push(`[${c.severity.toUpperCase()}] ${c.title}`)
        if (c.description) lines.push(`  ${c.description}`)
      })
    lines.push('')
  }

  // Friction & Flow — only if caller has permission
  if (includeFF && b.frictionAndFlow?.length > 0) {
    lines.push('FRICTION & FLOW  [INTERNAL ONLY]')
    lines.push('─────────────────────────────────────')
    b.frictionAndFlow.forEach(e => {
      lines.push(`${e.factorType}: ${e.personName}${e.personRole ? ` — ${e.personRole}` : ''}${e.company ? ` (${e.company})` : ''}`)
      if (e.notes) lines.push(`  ${e.notes}`)
    })
    lines.push('')
  }

  lines.push('═══════════════════════════════════════')
  lines.push('End of Handoff Summary')

  return lines.join('\n')
}

export function HandoffSummary({ production, bible, currentUserRole }) {
  const [generated, setGenerated] = useState(false)
  const [copied, setCopied] = useState(false)

  const isAdminOrSup = currentUserRole === ROLES.ADMIN || currentUserRole === ROLES.SUPERVISOR
  const b = bible || {}
  const openConcerns = (b.concerns || []).filter(c => c.status === 'Open')
    .sort((a, z) => ({ High: 0, Medium: 1, Low: 2 }[a.severity] - { High: 0, Medium: 1, Low: 2 }[z.severity]))

  const handleCopy = async () => {
    const text = buildPlainText(production, b, isAdminOrSup)
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      // Fallback for environments without clipboard API
      const el = document.createElement('textarea')
      el.value = text
      document.body.appendChild(el)
      el.select()
      document.execCommand('copy')
      document.body.removeChild(el)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    }
  }

  const handlePrint = () => window.print()

  if (!generated) {
    return (
      <section className="flex flex-col items-center justify-center py-16 text-center">
        <div className="w-14 h-14 rounded-2xl bg-orbital-muted flex items-center justify-center mb-4">
          <FileText size={24} className="text-orbital-subtle" />
        </div>
        <h3 className="font-semibold text-orbital-text mb-2">Generate Handoff Summary</h3>
        <p className="text-sm text-orbital-subtle max-w-sm mb-6">
          Compiles all Bible sections into a clean briefing document. Use it to hand off this production to any team member with full context in minutes.
        </p>
        <button onClick={() => setGenerated(true)} className="btn-primary">
          <FileText size={15} /> Generate Handoff
        </button>
      </section>
    )
  }

  return (
    <section>
      {/* Actions bar */}
      <div className="flex items-center justify-between mb-5 flex-wrap gap-3">
        <h3 className="font-semibold text-orbital-text">Handoff Summary</h3>
        <div className="flex gap-2">
          <button onClick={() => setGenerated(false)} className="btn-ghost text-xs py-1.5">
            <RefreshCw size={13} /> Regenerate
          </button>
          <button onClick={handleCopy} className={clsx('btn-secondary text-xs py-1.5 transition-colors', copied && 'text-green-400')}>
            {copied ? <><Check size={13} /> Copied!</> : <><ClipboardCopy size={13} /> Copy</>}
          </button>
          <button onClick={handlePrint} className="btn-secondary text-xs py-1.5 print:hidden">
            <Printer size={13} /> Print
          </button>
        </div>
      </div>

      {/* Summary document — print:block ensures this is the only thing that prints */}
      <div id="handoff-print-area" className="space-y-6 print:text-black print:bg-white">

        {/* Production header */}
        <div className="card p-5 print:border print:border-gray-300 print:rounded-none print:shadow-none">
          <div className="flex items-start justify-between gap-4 flex-wrap mb-1">
            <div>
              <p className="text-xs text-orbital-subtle uppercase tracking-widest mb-1 print:text-gray-500">Production Handoff</p>
              <h1 className="text-xl font-bold text-orbital-text print:text-black">{production.name}</h1>
              <p className="text-orbital-subtle print:text-gray-600">{production.client}</p>
            </div>
            <div className="text-right text-xs text-orbital-subtle print:text-gray-500">
              <p>Generated {format(new Date(), 'MMM d, yyyy h:mm a')}</p>
              <p className="mt-0.5">{production.status} · {production.productionType}</p>
            </div>
          </div>
          <div className="flex flex-wrap gap-4 mt-3 text-xs text-orbital-subtle print:text-gray-600">
            <span>{production.locationType === 'In-House (Orbital Studios)' ? 'Orbital Studios' : production.locationAddress || 'Mobile'}</span>
            {production.startDate && (
              <span>
                {format(parseISO(production.startDate), 'MMM d, yyyy')}
                {production.endDate && ` – ${format(parseISO(production.endDate), 'MMM d, yyyy')}`}
              </span>
            )}
          </div>
        </div>

        {/* Key Players */}
        {b.keyPlayers?.length > 0 && (
          <SummarySection title="Key Players">
            <div className="grid sm:grid-cols-2 gap-3">
              {b.keyPlayers.map(p => (
                <div key={p.id} className="p-3 rounded-lg bg-orbital-muted border border-orbital-border print:border-gray-200 print:bg-gray-50">
                  <p className="font-medium text-sm text-orbital-text print:text-black">{p.name}</p>
                  <p className="text-xs text-orbital-subtle print:text-gray-600">
                    {[p.role, p.company].filter(Boolean).join(' · ')} · <span className="font-medium">{p.tag}</span>
                  </p>
                  {p.phone && <p className="text-xs text-orbital-subtle mt-1 print:text-gray-600">📞 {p.phone}</p>}
                  {p.email && <p className="text-xs text-orbital-subtle print:text-gray-600">✉ {p.email}</p>}
                  {p.notes && <p className="text-xs text-orbital-subtle mt-1 italic print:text-gray-500">{p.notes}</p>}
                </div>
              ))}
            </div>
          </SummarySection>
        )}

        {/* Documents received */}
        {b.documents?.length > 0 && (
          <SummarySection title="Documents Received">
            <div className="space-y-2">
              {b.documents.map(d => (
                <div key={d.id} className="flex items-start gap-2 text-sm">
                  <span className="text-orbital-subtle print:text-gray-400 mt-0.5">•</span>
                  <div>
                    <span className="text-orbital-text print:text-black font-medium">{d.name}</span>
                    {d.dateReceived && <span className="text-orbital-subtle print:text-gray-500 ml-2 text-xs">received {format(parseISO(d.dateReceived), 'MMM d, yyyy')}</span>}
                    {d.notes && <p className="text-xs text-orbital-subtle print:text-gray-500 mt-0.5">{d.notes}</p>}
                  </div>
                </div>
              ))}
            </div>
          </SummarySection>
        )}

        {/* Open concerns */}
        {openConcerns.length > 0 && (
          <SummarySection title={`Open Concerns (${openConcerns.length})`}>
            <div className="space-y-2">
              {openConcerns.map(c => (
                <div key={c.id} className="flex items-start gap-3 p-3 rounded-lg bg-orbital-muted border border-orbital-border print:border-gray-200">
                  <span className={clsx('text-xs font-medium px-2 py-0.5 rounded mt-0.5 flex-shrink-0 print:border',
                    c.severity === 'High' ? 'bg-red-500/15 text-red-400 print:border-red-300 print:text-red-700' :
                    c.severity === 'Medium' ? 'bg-amber-500/15 text-amber-400 print:border-amber-300 print:text-amber-700' :
                    'bg-zinc-600/30 text-zinc-400 print:border-gray-300 print:text-gray-600'
                  )}>
                    {c.severity}
                  </span>
                  <div>
                    <p className="text-sm font-medium text-orbital-text print:text-black">{c.title}</p>
                    {c.description && <p className="text-xs text-orbital-subtle print:text-gray-600 mt-0.5">{c.description}</p>}
                  </div>
                </div>
              ))}
            </div>
          </SummarySection>
        )}

        {/* Friction & Flow — Admin/Supervisor only */}
        {isAdminOrSup && b.frictionAndFlow?.length > 0 && (
          <SummarySection
            title="Friction & Flow"
            badge={<span className="flex items-center gap-1 px-2 py-0.5 rounded bg-orbital-muted border border-orbital-border text-xs text-orbital-subtle print:hidden"><span>🔒</span> Internal Only</span>}
          >
            <div className="space-y-2">
              {b.frictionAndFlow.map(e => (
                <div key={e.id} className="flex items-start gap-3 p-3 rounded-lg bg-orbital-muted border border-orbital-border print:border-gray-200">
                  <span className={clsx('text-xs font-medium px-2 py-0.5 rounded mt-0.5 flex-shrink-0',
                    e.factorType === 'Positive Contributor'
                      ? 'bg-green-500/10 text-green-400'
                      : 'bg-amber-500/10 text-amber-400'
                  )}>
                    {e.factorType === 'Positive Contributor' ? '↑' : '↓'} {e.factorType}
                  </span>
                  <div>
                    <p className="text-sm font-medium text-orbital-text print:text-black">{e.personName}</p>
                    {(e.personRole || e.company) && (
                      <p className="text-xs text-orbital-subtle print:text-gray-600">{[e.personRole, e.company].filter(Boolean).join(' · ')}</p>
                    )}
                    {e.notes && <p className="text-xs text-orbital-subtle print:text-gray-600 mt-0.5">{e.notes}</p>}
                  </div>
                </div>
              ))}
            </div>
          </SummarySection>
        )}

        {/* Empty state */}
        {!b.keyPlayers?.length && !b.documents?.length && !openConcerns.length && (
          <div className="card p-8 text-center">
            <p className="text-orbital-subtle text-sm">No Bible data yet. Add entries to Key Players, Documents, and Concerns to populate the handoff summary.</p>
          </div>
        )}
      </div>
    </section>
  )
}

function SummarySection({ title, children, badge }) {
  return (
    <div>
      <div className="flex items-center gap-2 mb-3">
        <h4 className="font-semibold text-orbital-text print:text-black">{title}</h4>
        {badge}
      </div>
      {children}
    </div>
  )
}
